default_platform(:ios)

platform :ios do
  desc "Build production release and deploy to Firebase App Distribution"
  lane :distribute do
    firebase_app_distribution(
          app: "1:540936468411:ios:cbfa420b2201e3c7bff69e",
          service_credentials_file: "/Users/kristian/Documents/Kristian/bottleshop/bottleshop3veze-firebase_app_distribution.json",
          groups: "ios-testers",
          ipa_path: "/Users/kristian/Documents/Kristian/bottleshop/bottleshop-cloud-platform/apps/admin/build/ios/ipa/Bottleshop Admin.ipa",
          release_notes: "Let's go bottleroom"
     )
  end
end
