name: bottleshop_admin
description: Admin app for Bottleshop Tri Veze
version: 1.4.3+16
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  firebase_storage: ^11.0.14
  firebase_auth: ^4.2.9
  firebase_core_platform_interface: ^4.5.3
  firebase_analytics: ^10.1.4
  cloud_firestore: ^4.4.3
  cloud_functions: ^4.0.11
  firebase_crashlytics: ^3.0.15
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1
  tuple: ^2.0.0
  intl: ^0.17.0
  collection: ^1.16.0
  dropdown_search: ^5.0.2
  image: ^3.3.0
  path_provider: ^2.0.11
  path: ^1.8.1
  flutter_hooks: ^0.17.0
  hooks_riverpod: 0.14.0+4
  diacritic: ^0.1.3
  http: ^0.13.1
  sliver_tools: ^0.2.7
  equatable: ^2.0.3
  streamed_items_state_management:
    git:
      url: https://github.com/cloudis-dev/streamed-items-state-management.git
      ref: 689d8a48a564940b145444135882dc5e855e7517
  package_info_plus: ^3.0.2
  version: ^3.0.2
  url_launcher: ^6.1.5
  optional: ^6.1.0+1
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Bottleshop
      fonts:
        - asset: assets/icons/Bottleshop.ttf
  assets:
    - assets/images/
