/// Flutter icons Bottleshop
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bottleshop
///      fonts:
///       - asset: fonts/Bottleshop.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Bottleshop {
  Bottleshop._();

  static const _kFontFam = 'Bottleshop';
  static const dynamic _kFontPkg = null;

  static const IconData circledOne =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circledTwo =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circledThree =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ballot =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkCircleOutline24px =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
