include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/**/*generated_plugin*.dart"
    - "lib/generated/**"
    - "lib/l10n/**"
    - "build/**"
    - "assets/**"

  language:
    strict-inference: true
    strict-raw-types: true

  errors:
    public_member_api_docs: ignore
    included_file_warning: ignore
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    missing_required_param: error

linter:
  rules:
    type_annotate_public_apis: false
    avoid_classes_with_only_static_members: false
    prefer_double_quotes: false
    always_specify_types: false
    prefer_expression_function_bodies: false
    always_put_required_named_parameters_first: false
    flutter_style_todos: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    avoid_annotating_with_dynamic: false
    avoid_function_literals_in_foreach_calls: false
    prefer_relative_imports: false
    no_default_cases: false
    prefer_mixin: false
    avoid_print: true
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    implementation_imports: false
    unawaited_futures: true
