name: delivery
description: Bottleshop 3 Veže Delivery App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.0+177

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_core: ^1.20.0
  firebase_messaging: ^13.0.0
  firebase_auth: ^3.6.1
  cloud_firestore: ^3.4.2
  firebase_crashlytics: ^2.8.6
  firebase_analytics: ^9.3.0
  firebase_storage: ^10.3.4
  cloud_functions: ^3.3.3
  firebase_in_app_messaging: ^0.6.0+23
  flutter_local_notifications: ^9.8.0+1
  google_fonts: ^3.0.1
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^4.4.1
  sign_in_with_apple: ^4.1.0
  cupertino_icons: ^1.0.4
  flutter_sticky_header: ^0.6.0
  datetime_picker_formfield: ^2.0.0
  animations: ^2.0.2
  tuple: ^2.0.0
  http: ^0.13.4
  flutter_stripe: ^2.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.3
  state_notifier: ^0.7.1
  equatable: ^2.0.3
  device_info: ^2.0.3
  shared_preferences: ^2.0.8
  carousel_slider: ^4.0.0
  overlay_support: ^2.0.1
  crypto: ^3.0.1
  form_field_validator: ^1.1.0
  about: ^2.1.0
  diacritic: ^0.1.3
  sliver_tools: ^0.2.5
  flutter_markdown: ^0.6.8
  pdfx: ^2.2.0
  pay: ^1.0.6
  streamed_items_state_management:
    git:
      url: https://github.com/cloudis-dev/streamed-items-state-management.git
      ref: 689d8a48a564940b145444135882dc5e855e7517
  meta: ^1.7.0
  package_info_plus: ^1.3.0
  version: ^3.0.2
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  badges: ^2.0.2
  flutter_svg: ^1.1.4
  intl: 0.17.0
  dartz: ^0.10.1
  logging: ^1.0.2
  align_positioned: ^3.0.0
  octo_image: ^1.0.1
  routeborn: ^0.4.3
  rxdart: ^0.27.3
  infinite_scroll_pagination: ^3.1.0
  js: ^0.6.3
  flutter_scroll_to_top:
    git:
      url: https://github.com/KristianBalaj/flutter_scroll_to_top.git
      ref: 21d47cab93a52e83eed910d3564278623c830e88
  responsive_framework: ^0.2.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/markdown/
    - assets/fonts/
