name: delivery
description: Bottleshop3veze Delivery app
version: 2.0.0+195
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cloud_firestore: ^3.1.15
  cloud_functions: ^3.2.15
  firebase_analytics: ^9.1.8
  firebase_app_check: ^0.0.6+12
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.0
  firebase_in_app_messaging: ^0.6.0+14
  firebase_messaging: ^11.4.0
  firebase_storage: ^10.2.16
  intl: ^0.17.0
  flutter_local_notifications: ^9.5.2
  google_fonts: ^3.0.0
  google_sign_in: ^5.3.1
  flutter_sticky_header: ^0.6.2
  datetime_picker_formfield: ^2.0.0
  animations: ^2.0.2
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^2.0.0-dev.8
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  crypto: ^3.0.2
  form_field_validator: ^1.1.0
  about: ^2.1.1
  diacritic: ^0.1.3
  sliver_tools: ^0.2.6
  flutter_markdown: ^0.6.9+1
  native_pdf_view: ^6.0.0+1
  meta: ^1.7.0
  package_info_plus: ^1.4.2
  version: ^2.0.0
  url_launcher: ^6.1.2
  uuid: ^3.0.6
  badges: ^2.0.2
  align_positioned: ^3.0.0
  octo_image: ^1.0.2
  infinite_scroll_pagination: ^3.1.0
  device_info_plus: ^3.2.3
  platform: ^3.1.0
  flutter_stripe: ^3.0.0
  flutter_stripe_web: ^1.0.0
  pay: ^1.0.8
  http: ^0.13.4
  flutter_native_splash: ^2.2.1
  vrouter: ^1.2.1
  dartz: ^0.10.1
  rxdart: ^0.27.3
  flutter_dotenv: ^5.0.2
  pdfx: ^1.0.1+1
  flutter_loggy: ^2.0.1
  loggy: ^2.0.1+1
  flutter_facebook_auth: ^4.3.4
  sign_in_with_apple: ^4.0.0
  json_annotation: ^4.5.0
  overlay_support: ^2.0.0
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

dependency_overrides:
  flutter_svg: ^1.0.3
  xml: ^5.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/markdown/
    - assets/fonts/
    - assets/json/
    - .env

flutter_native_splash:
  image: 'assets/images/splash_branding.png'
  color: '#161613'
  android: false
  ios: false
  web: true
  web_image_mode: center
  fullscreen: true
