// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProductionFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Taken from https://console.cloud.google.com/apis/credentials?project=bottleshop-3-veze-dev-54908
  /// Under "OAuth 2.0 Client IDs"
  static String get currentClientId {
    if (kIsWeb) {
      return '540936468411-44uajovjnes48qd3b6ditirj8336um5c.apps.googleusercontent.com';
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return '540936468411-2bef528sv3kf6pvnchcggc1aoqolbpsc.apps.googleusercontent.com';
      case TargetPlatform.iOS:
        return '540936468411-32eqnks9pqj6tamosjq8t2uik97q2fth.apps.googleusercontent.com';
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEIArskQbVY3HB8saRUZYMHfHeu78jXCM',
    appId: '1:540936468411:web:5d23dc6a7d01fe16bff69e',
    messagingSenderId: '540936468411',
    projectId: 'bottleshop3veze-delivery',
    authDomain: 'bottleshop3veze-delivery.firebaseapp.com',
    databaseURL: 'https://bottleshop3veze-delivery.firebaseio.com',
    storageBucket: 'bottleshop3veze-delivery.appspot.com',
    measurementId: 'G-59N5H07K5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0-koT0ru49lajwgG3egozdjbZ1_7Nfw',
    appId: '1:540936468411:android:f81fc523202f0097bff69e',
    messagingSenderId: '540936468411',
    projectId: 'bottleshop3veze-delivery',
    databaseURL: 'https://bottleshop3veze-delivery.firebaseio.com',
    storageBucket: 'bottleshop3veze-delivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWdUFIdbwtIFlZ_fp7qOGIUOwKjeD6gtc',
    appId: '1:540936468411:ios:74b4bb86d789e402bff69e',
    messagingSenderId: '540936468411',
    projectId: 'bottleshop3veze-delivery',
    databaseURL: 'https://bottleshop3veze-delivery.firebaseio.com',
    storageBucket: 'bottleshop3veze-delivery.appspot.com',
    iosBundleId: 'sk.bottleshop3veze.bottleshopdeliveryapp',
  );
}
